---
envAlias: dev
domainAPI: api-dev.please-scan.com
domainWeb: scan-dev.please-scan.com
domainWebIp: mrdjs.rtarf-prod.its-software-services.com
domainBn: bn-dev.please-scan.com
theHiveLoaderSuspend: true
uptimeLoaderSuspend: true
backupAdsSuspend: true
backupSupersetSuspend: true
feedLoaderSuspend: true
