---
envAlias: dev
domainAPI: mrdjs-dev.please-scan.com
domainWeb: defnex.please-scan.com
domainWebIp: mrdjs.rtarf-prod.its-software-services.com
domainBn: bn-dev.please-scan.com
theHiveLoaderSuspend: true
uptimeLoaderSuspend: true
backupAdsSuspend: true
backupSupersetSuspend: true
feedLoaderSuspend: true
caseTransformerSuspend: true
