---
envAlias: prod
domainAPI: ads-api.rtarf-prod.its-software-services.com
domainWeb: mrdjs.rtarf-prod.its-software-services.com
domainWeb2: mrdjs2.elk.cyber.rtarf.mi.th
domainWebAnalytic: ads-analytic.rtarf-prod.its-software-services.com
domainWebAnalytic2: mainsilo.elk.cyber.rtarf.mi.th
domainWebIp: 10.141.98.40
domainBn: bn.rtarf-prod.its-software-services.com
theHiveLoaderSuspend: false
uptimeLoaderSuspend: false
backupAdsSuspend: false
backupSupersetSuspend: false
feedLoaderSuspend: false
caseTransformerSuspend: false
