apiVersion: v2
name: helm-erp
description: A Helm chart for ADS

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  ### pgSQL ###
  - name: "postgresql"
    alias: postgresql-ads
    condition: postgresql-ads.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "15.2.9"

  ### ads-api ###
  - name: "generic-app"
    alias: ads-api
    condition: ads-api.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  ### redis ###
  - name: "redis"
    alias: redis
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "18.13.0"
