{{ if eq .Values.envAlias "dev" }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: ads-api-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: ads-api-secret        # name of the k8s Secret to be created
  data:
  - secretKey: API_AUTHEN_PASSWORD
    remoteRef:
      key: ads-api-password
      property: API_AUTHEN_PASSWORD
      version: latest

  - secretKey: API_AUTHEN_USER
    remoteRef:
      key: ads-api-password
      property: API_AUTHEN_USER
      version: latest

  - secretKey: API_ENDPOINT
    remoteRef:
      key: ads-api-password
      property: API_ENDPOINT
      version: latest

{{- end -}}
