{{ if eq .Values.envAlias "prod" }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ads-pg-backup-superset
spec:
  # kubectl create job --from=cronjob/ads-pg-backup-superset ads-pg-backup-superset-001 -n ads-prod
  suspend: {{ .Values.backupSupersetSuspend }}
  schedule: "0 */4 * * *" # Every 4 hours
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: cron-script
            image: asia-southeast1-docker.pkg.dev/its-artifact-commons/rtarf/ads-jobs:{{ .Values.adsJob.imageTag }}
            imagePullPolicy: IfNotPresent
            command:
            - bash
            args:
            - /scripts/backup-postgres-db.bash
            env:
            - name: BACKUP_NAME_PREFIX
              value: "postgres"

            - name: EXTENSION
              value: "superset-{{ .Values.envAlias }}"

            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gcp-sa.json

            - name: TARGET_NS
              value: "superset"

            - name: TARGET_POD
              value: "superset-production-postgresql-0"

            - name: GCS_FOLDER
              value: "superset-backup"

            volumeMounts:
            - name: temp-dir
              mountPath: /data/temp

            - name: secrets
              readOnly: true
              mountPath: "/secrets"

          restartPolicy: OnFailure

          volumes:
          - name: temp-dir
            emptyDir: {}

          - name: secrets
            secret:
              secretName: gcp-sa
{{- end -}}
