{{ if eq .Values.envAlias "prod" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ads-api-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: ads-api-secret        # name of the k8s Secret to be created
  data:
  - secretKey: API_AUTHEN_PASSWORD
    remoteRef:
      key: initial-secret
      property: ADS_API_AUTHEN_PASSWORD

  - secretKey: API_AUTHEN_USER
    remoteRef:
      key: initial-secret
      property: ADS_API_AUTHEN_USER

  - secretKey: API_ENDPOINT
    remoteRef:
      key: initial-secret
      property: ADS_API_ENDPOINT
{{- end -}}
