apiVersion: batch/v1
kind: CronJob
metadata:
  name: blacklist-cache-loader
spec:
  # kubectl create job --from=cronjob/blacklist-cache-loader blacklist-loader-001 -n ads-dev
  schedule: "*/15 * * * *" # Every 15 minute
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: cron-script
            image: asia-southeast1-docker.pkg.dev/its-artifact-commons/rtarf/ads-jobs:{{ .Values.adsJob.imageTag }}
            imagePullPolicy: IfNotPresent
            command:
            - ruby
            args:
            - /scripts/blacklist-cache-loader.rb
            env:
            - name: REDIS_HOST
              value: redis-master

            - name: ORG_ID
              value: default

            volumeMounts:
            - name: temp-dir
              mountPath: /data/temp

          restartPolicy: OnFailure

          volumes:
          - name: temp-dir
            emptyDir: {}
