apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ads-api-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  tls:
    - hosts:
      - {{ .Values.domainAPI }}
      secretName: ads-api-cert
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.domainAPI }}"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: ads-{{ .Values.envAlias }}-ads-api
            port:
              number: 80
