apiVersion: batch/v1
kind: CronJob
metadata:
  name: cases-transform
spec:
  # kubectl create job --from=cronjob/cases-transform cases-transform-001 -n ads-prod
  suspend: {{ .Values.caseTransformerSuspend }}
  schedule: "5 * * * *" # Every นาทีที่ 5 ของทุกๆ ชั่วโมง
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: cron-script
            image: asia-southeast1-docker.pkg.dev/its-artifact-commons/rtarf/ads-ai-jobs:{{ .Values.adsJobAI.imageTag }}
            imagePullPolicy: IfNotPresent
            command:
            - python
            args:
            - /scripts/cases-transformer.py
            env:
            - name: HF_HOME
              value: /data/hf

            - name: PG_HOST
              value: "postgresql-ads"

            - name: PG_DB
              value: "ads"

            - name: PG_USER
              value: "postgres"

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ads-postgres-secret
                  key: adminPasswordKey
                  optional: false

            - name: START_CASE_NO
              value: "1"

            volumeMounts:
            - name: temp-dir
              mountPath: /data/temp

            - name: hf
              mountPath: /data/hf

          restartPolicy: OnFailure

          volumes:
          - name: temp-dir
            emptyDir: {}

          - name: hf
            persistentVolumeClaim:
              claimName: cases-transform-pvc
