{{ if eq .Values.envAlias "dev" }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: ads-postgres-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: ads-postgres-secret       # name of the k8s Secret to be created
  data:
  - secretKey: adminPasswordKey
    remoteRef:
      key: ads-postgresql-{{ .Values.envAlias }}
      property: PG_PASSWORD # In the future we will use from another property
{{- end -}}
