{{ if eq .Values.envAlias "prod" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ads-postgres-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: ads-postgres-secret   # name of the k8s Secret to be created
  data:
  - secretKey: adminPasswordKey
    remoteRef:
      key: initial-secret
      property: ES_PASSWORD2
{{- end -}}
