ads-analytic-web:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: API_PATH
        value: "https://defnex-api.please-scan.com"

      - name: API_KEY
        value: "will move this to secret"
