ads-analytic-web:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: API_PATH
        value: "https://ads-api.rtarf-prod.its-software-services.com"

      - name: API_AUTHEN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ads-api-secret
            key: API_AUTHEN_PASSWORD

      - name: ES_URL
        value: "https://localhost:9200"

      - name: ES_USER
        value: "es-dummy-user-notuse"

      - name: ES_PASS
        value: "es-dummy-password-notuse"

      - name: DATABASE_URL
        value: "postgresql://postgres:notuse@xxxxx:5432/notused"
