ads-analytic-web:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: API_PATH
        value: "https://defnex-api.please-scan.com"

      - name: API_AUTHEN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ads-api-secret
            key: API_AUTHEN_PASSWORD

      - name: ES_URL
        value: "http://es-host.dummy.comxx"

      - name: ES_USER
        value: "es-dummy-user-notuse"

      - name: ES_PASS
        value: "es-dummy-password-notuse"
