ads-web:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "3000"

      - name: NUXT_URL_GEOIP_ATTACK_MAP
        value: "https://geoip-map.rtarf-prod.its-software-services.com/"

      - name: NUXT_URL_MACHINE_STATUS
        value: "https://uptime-kuma.rtarf-prod.its-software-services.com/dashboard/"

      - name: IDP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_ID

      - name: IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_SECRET

      - name: IDP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_ENDPOINT
