ads-web:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "3000"

      - name: NUXT_PUBLIC_GEO_IP_URL
        value: "https://geoip-map.rtarf-prod.its-software-services.com/"

      - name: NUXT_PUBLIC_MACHINE_STATUS_URL
        value: "https://superset.rtarf-prod.its-software-services.com/superset/dashboard/p/KWMgDVYlar7/" #"https://uptime-kuma.rtarf-prod.its-software-services.com/dashboard/"

      - name: NUXT_KEYCLOAK_IDP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_ID

      - name: NUXT_KEYCLOAK_IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_SECRET

      - name: NUXT_KEYCLOAK_IDP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_ENDPOINT

      - name: NUXT_API_PATH
        value: "https://ads-api.rtarf-prod.its-software-services.com"
