ads-web:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "3000"

      - name: NUXT_PUBLIC_GEO_IP_URL
        value: "https://geoip-map.rtarf-prod.its-software-services.com/"

      - name: NUXT_PUBLIC_MACHINE_STATUS_URL
        value: "https://superset.rtarf-prod.its-software-services.com/superset/dashboard/3ac28d3b-ee7e-415f-864e-d5119abbee23/?standalone=true&native_filters_key=DA_GqL-hMbFj0y_bQrEVQGcxeK6zM5LrQXeMRldf41SPqMpEk6QxNSTdsJUUgpB6" 
        #"https://uptime-kuma.rtarf-prod.its-software-services.com/dashboard/"

      - name: NUXT_KEYCLOAK_IDP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_ID

      - name: NUXT_KEYCLOAK_IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_SECRET

      - name: NUXT_KEYCLOAK_IDP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_ENDPOINT

      - name: NUXT_API_PATH
        value: "https://ads-api.rtarf-prod.its-software-services.com"

      # Dashboard
      - name: NUXT_DASHBOARD_URL01 # Zeek Event Summary
        value: "https://superset.rtarf-prod.its-software-services.com/superset/dashboard/p/qDKmB5Nl0vw/"

      - name: NUXT_DASHBOARD_URL02 # Blacklist Summary
        value: "https://superset.rtarf-prod.its-software-services.com/superset/dashboard/p/yYwmEVAgxnJ/"

      - name: NUXT_DASHBOARD_URL03 # Crowdstrie Summary
        value: "https://superset.rtarf-prod.its-software-services.com/superset/dashboard/p/7YKg12bR0Ze/"

      - name: NUXT_DASHBOARD_URL04 # IoC Summary
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      - name: NUXT_DASHBOARD_URL05 # Zeek Summary (Suricata)
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      - name: NUXT_DASHBOARD_URL06 # Zeek Summary (Intel)
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      - name: NUXT_DASHBOARD_URL07 # Zeek Summary (HTTP)
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      - name: NUXT_DASHBOARD_URL08 # Zeek Summary (Files)
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      - name: NUXT_DASHBOARD_URL09 # Zeek Summary (SSL)
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      - name: NUXT_DASHBOARD_URL10 # Zeek Summary (DNS)
        value: "https://www.youtube.com/watch?v=_e3LyCL2F0g"

      # Tools
      - name: NUXT_TOOL_URL01 # Kibana
        value: "https://kibana-soc.rtarf-prod.its-software-services.com/"

      - name: NUXT_TOOL_URL02 # Kafka
        value: "https://kafka-ui.rtarf-prod.its-software-services.com/"

      - name: NUXT_TOOL_URL031 # Metalog #1
        value: "https://10.141.98.153/"

      - name: NUXT_TOOL_URL032 # Metalog #2
        value: "https://10.141.98.154/"

      - name: NUXT_TOOL_URL033 # Metalog #3
        value: "https://10.141.98.155/"

      - name: NUXT_TOOL_URL041 # Net Approve #1
        value: "https://10.141.98.156/"

      - name: NUXT_TOOL_URL042 # Net Approve #2
        value: "https://10.141.98.157/"

      - name: NUXT_TOOL_URL043 # Net Approve #3
        value: "https://10.141.98.158/"

      - name: NUXT_TOOL_URL044 # Net Approve #4
        value: "https://10.141.98.159/"

      - name: NUXT_TOOL_URL05 # GeoIP
        value: "https://geoip-map.rtarf-prod.its-software-services.com/"

      - name: NUXT_TOOL_URL06 # Superset
        value: "https://superset.rtarf-prod.its-software-services.com/"

      - name: NUXT_TOOL_URL07 # Loki
        value: "https://grafana-loki.rtarf-prod.its-software-services.com/"

      - name: NUXT_TOOL_URL08 # Prometheus
        value: "https://grafana-k8s.rtarf-prod.its-software-services.com/"
