postgresql-ads:
  enabled: true
  fullnameOverride: postgresql-ads
  auth:
    database: ads
    existingSecret: ads-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey

  primary:
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 2
        memory: 1024Mi

  image:
    registry: asia-southeast1-docker.pkg.dev
    repository: its-artifact-commons/utils/postgresql
    tag: "v16.2.0-2"
