{{ if eq .Values.envAlias "dev" }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: idp-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: idp-secret        # name of the k8s Secret to be created
  data:
  - secretKey: IDP_CLIENT_ID
    remoteRef:
      key: mrdjs-idp
      property: IDP_CLIENT_ID
      version: latest

  - secretKey: IDP_CLIENT_SECRET
    remoteRef:
      key: mrdjs-idp
      property: IDP_CLIENT_SECRET
      version: latest

  - secretKey: IDP_ENDPOINT
    remoteRef:
      key: mrdjs-idp
      property: IDP_ENDPOINT
      version: latest
{{- end -}}
