apiVersion: v1
kind: ConfigMap
metadata:
  name: oui-map-cm
  annotations:
    checksum/config1: {{ .Files.Get "configs/oui-map.cfg" | sha256sum }}
data:
  oui-map.cfg: |-
{{ .Files.Get "configs/oui-map.cfg" |  indent 4 }}
