apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ads-web-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  {{ if eq .Values.envAlias "prod" }}
  tls:
    - hosts:
      - {{ .Values.domainWeb }}
      secretName: ads-web-cert
  {{- end -}}
  rules:
  - host: "{{ .Values.domainWeb }}"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: ads-{{ .Values.envAlias }}-ads-web
            port:
              number: 80
