{{ if eq .Values.envAlias "prod" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ads-web-cert
spec:
  secretName: ads-web-cert
  dnsNames:
    - {{ .Values.domainWeb }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
{{- end -}}
